"""Canonical observation and raw-state indices defined by the C++ environment.

Keep this module synchronized with bg/src/obs.cpp, bg/src/obs.h, and bg/src/env.h.
All Python code must use these absolute indices instead of offsets from the end.
"""

POINTS_DIM = 24
VECTOR_CHANNELS = 10

OBS_POINTS = 0
OBS_OPP_POINTS = 24
OBS_BLOTS = 48
OBS_OPP_BLOTS = 72
OBS_ANCHORS = 96
OBS_OPP_ANCHORS = 120
OBS_HIT_PROB_MINE = 144
OBS_COVER_PROB_MINE = 168
OBS_HIT_PROB_OPP = 192
OBS_COVER_PROB_OPP = 216

OBS_SCALAR_BASE = 240
OBS_BAR = 240
OBS_OFF = 241
OBS_OPP_BAR = 242
OBS_OPP_OFF = 243
OBS_PIP_MINE = 244
OBS_PIP_OPP = 245
OBS_BLOTS_MINE = 246
OBS_BLOTS_OPP = 247
OBS_ANCHORS_MINE = 248
OBS_ANCHORS_OPP = 249
OBS_BLOT_PIPS_MINE = 250
OBS_BLOT_PIPS_OPP = 251
OBS_ANCHOR_PIPS_MINE = 252
OBS_ANCHOR_PIPS_OPP = 253
OBS_MINE_SCORE = 254
OBS_OPP_SCORE = 255
OBS_DAVE_VALUE = 256
OBS_MY_LEFT = 257
OBS_OPP_LEFT = 258
OBS_CUBE_AVAILABLE_MINE = 259
OBS_CUBE_AVAILABLE_OPP = 260
OBS_IS_CRAWFORD_GAME = 261
OBS_DOUBLE_OFFERED = 262
OBS_MINE_ALL_IN_HOME = 263
OBS_OPP_ALL_IN_HOME = 264
OBS_RACE_STAGE_NO_HIT = 265
OBSERVATION_DIM = 266

# Canonical raw state indices from bg/src/env.h.
RAW_PLY = 52
RAW_WHITE_SCORE = 53
RAW_BLACK_SCORE = 54
RAW_DAVE_VALUE = 55
RAW_N_GAMES = 56
RAW_WHITE_TO_MOVE = 57
RAW_CRAWFORD_USED = 58
RAW_IS_CRAWFORD_GAME = 59
RAW_FIRST_TURN = 60
RAW_WHITE_TO_MOVE_DUP = 61
RAW_SECOND_PLAYER_WHITE = 62
RAW_CUBE_OWNER = 63
RAW_PREVIOUS_GAME_LOSER = 64
RAW_ACCEPT_DOUBLE_NEXT_OFFER = 65
RAW_CUBE_AVAILABLE_MINE = 66
RAW_CUBE_AVAILABLE_OPP = 67
RAW_DOUBLE_OFFERED = 68
RAW_STATE_DIM = 69
